version: "3.1"

services:
  APPUI:
    container_name: fe-asset-management
    image: react-asset-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    stdin_open: true  