name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy-run-e2e:
    runs-on: ubuntu-latest
    steps:
       - name: Clone BE repo
         uses: actions/checkout@master
         with:
          repository: AndreivanP/BE_PatrimonyManagement
          token: ${{ secrets.gha_pta || github.token }}
       - name: Generate jar artifact
         run: mvn install -DskipTests
       - name: Build back end docker images
         run: docker-compose -f docker-compose-be.yml build
       - name: Create docker containers for API and Database
         run: docker-compose -f docker-compose-be.yml up -d
       - uses: actions/checkout@v2
         with:
          ref: ${{ github.event.pull_request.head.sha }}
       - name: Build front end related docker images
         run: |
          git status
          docker-compose -f docker-compose-fe.yml build
       - name: Create docker containers for FE app and Cypress runner
         run: docker-compose -f docker-compose-fe.yml up -d
       - name: Run e2e tests within cypress container
         run: docker-compose -f docker-compose-fe.yml exec -T e2e-runner npm run cy:regression
           
  deploy-in-production:
    needs: build-deploy-run-e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Yarn Install
          run: |
            yarn install
        - name: Production Build
          run: |
            yarn build
        - name: Deploy to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            SOURCE_DIR: "build"
     
