name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-be:
    runs-on: ubuntu-latest
    steps:
       - name: Clone BE repo
         uses: actions/checkout@master
         with:
          repository: AndreivanP/BE_PatrimonyManagement
          token: ${{ secrets.gha_pta || github.token }}
       - name: Generate jar artifact
         run: |
          pwd
          ls -ll -a
          mvn install -DskipTests
       - name: Build docker image
         run: docker-compose -f docker-compose-be.yml build
       - name: Create docker containers for API and Database
         run: docker-compose -f docker-compose-be.yml up -d

  build-fe:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
          ref: gha-test #${{ github.event.pull_request.head.sha }}
       - name: Build docker image
         run: |
          pwd
          ls -ll -a
          docker-compose -f docker-compose-fe.yml build
       - name: Create docker container for FE app
         run: docker-compose -f docker-compose-fe.yml up -d
